name: studentup_mobile
description: The first global virtual campus!

version: 0.0.5+7

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Pure UI
  cupertino_icons: ^0.1.2
  flutter_launcher_icons: ^0.7.2+1
  liquid_pull_to_refresh: ^1.1.1
  firestore_ui: ^1.6.0
  percent_indicator: ^2.1.1+1
  flutter_icons: ^0.1.4
  flip_panel: ^1.0.0
  flutter_clean_calendar: ^1.0.1
  flutter_villains: ^1.2.1

  #Plugins that save time
  email_validator: ^1.0.0
  flutter_auth_buttons: ^0.5.0
  flutter_inner_drawer: ^0.4.0
  flash: ^1.1.0+2
  page_transition: ^1.1.4
  expandable: ^3.0.0+1
  timeago: ^2.0.18
  flutter_staggered_grid_view: ^0.3.0
  flutter_cupertino_date_picker: ^1.0.12
  random_color: ^1.0.3
  rating_dialog: ^1.0.0

  #Device-related packages
  shared_preferences: ^0.5.3+4
  just_debounce_it: ^3.0.0+1
  file_picker: ^1.3.8
  image_cropper: ^1.0.2
  image_picker: ^0.6.1+4
  open_file: ^2.0.3

  #Utility Packages
  provider: ^3.1.0
  catcher: ^0.2.3
  get_it: ^1.0.3+2
  rxdart: ^0.22.1+1
  quiver: ^2.0.3
  connectivity: ^0.4.4
  path_provider: ^1.3.0
  equatable: ^0.5.1

  #Network-dependent packages
  cached_network_image: ^1.1.1
  firebase_core: ^0.4.0+8
  google_sign_in: ^4.0.6
  firebase_auth: ^0.14.0+2
  cloud_firestore: ^0.12.9
  firebase_storage: ^3.0.6
  firebase_messaging: ^5.1.3
  firebase_analytics: ^5.0.0
  #firebase_in_app_messaging: ^0.0.1+3
  algolia: ^0.1.6+1
  dio: ^2.1.16
  url_launcher: ^5.1.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/logo.png
    - assets/onboarding/
