name: studentup_mobile
description: The first global virtual campus!

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Pure UI
  cupertino_icons: ^0.1.2
  flutter_launcher_icons: ^0.7.2+1

  #Plugins that save time
  email_validator: ^1.0.0
  flutter_auth_buttons: ^0.5.0
  flutter_inner_drawer: ^0.4.0
  flash: ^1.1.0+2
  page_transition: ^1.1.4

  #Device-related packages
  shared_preferences: ^0.5.3+4
  just_debounce_it: ^3.0.0+1

  #Utility Packages
  provider: ^3.0.0+1
  catcher: ^0.2.3
  get_it: ^1.0.3+2
  rxdart: ^0.22.1+1

  #Network-dependent packages
  firebase_core: ^0.4.0+8
  google_sign_in: ^4.0.6
  firebase_auth: ^0.14.0+2
  cloud_firestore: ^0.12.9
  algolia: ^0.1.6+1
  firebase_messaging: ^5.1.3
  firebase_analytics: ^5.0.0
  cached_network_image: ^1.1.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/logo.png
    - assets/onboarding/
