name: ui_dev
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  feather_icons_flutter: ^4.7.4
  flutter_icons: ^0.1.4
  cached_network_image: ^1.1.0
  liquid_pull_to_refresh: ^1.1.1
  timeago: ^2.0.17
  percent_indicator: ^2.1.1
  flip_panel: ^1.0.0
  flutter_staggered_grid_view: ^0.3.0
  flutter_clean_calendar: ^1.0.1
  flutter_picker: ^1.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
