name: studentup
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #UI/Widgets
  cupertino_icons: ^0.1.2
  feather_icons_flutter: ^4.7.4
  flushbar: ^1.7.0
  flutter_inner_drawer: ^0.2.6
  page_transition: ^1.1.0
  shimmer: ^1.0.0
  liquid_swipe: ^1.0.2
  flutter_auth_buttons: ^0.5.0
  flutter_staggered_grid_view: ^0.3.0
  flutter_slidable: ^0.5.3

  #Development
  get_it: ^1.0.3+1
  provider: ^2.0.1+1
  rxdart: ^0.22.0
  catcher: ^0.2.0

  #Utilities
  email_validator: ^1.0.0
  shared_preferences: ^0.5.2+1
  connectivity: ^0.4.3+1
  cached_network_image: ^0.8.0
  flutter_typeahead: ^1.6.1
  liquid_pull_to_refresh: ^1.1.1

  #Networking/API
  google_sign_in: ^4.0.2
  firebase_core: ^0.4.0+3
  firebase_auth: ^0.11.1+5
  cloud_firestore: ^0.12.5+1
  #firebase_messaging: ^5.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
