name: studentup
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #UI/Widgets
  cupertino_icons: ^0.1.2
  flushbar: ^1.7.0
  flutter_inner_drawer: ^0.2.6
  page_transition: ^1.1.0
  shimmer: ^1.0.0
  intro_views_flutter: ^2.6.0
  flutter_auth_buttons: ^0.5.0

  #Development
  get_it: ^1.0.3+1
  provider: ^2.0.1+1
  rxdart: ^0.22.0

  #Utilities
  email_validator: ^1.0.0
  shared_preferences: ^0.5.2+1
  connectivity: ^0.4.3+1
  cached_network_image: ^0.8.0

  #Networking/API
  google_sign_in: ^4.0.2
  firebase_core: ^0.4.0+3
  firebase_auth: ^0.11.1+5
  cloud_firestore: ^0.12.5+1
  #firebase_messaging: ^5.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
